![Siguiente](https://dl.dropboxusercontent.com/u/2726997/img/_siguiente-plato.png)

[![NPM version](https://badge.fury.io/js/siguiente.png)](http://badge.fury.io/js/siguiente)
[![Build Status](https://api.travis-ci.org/pateketrueke/siguiente.png?branch=master)](https://travis-ci.org/pateketrueke/siguiente?branch=master)
[![Coverage Status](https://codecov.io/github/pateketrueke/siguiente/coverage.svg?branch=master)](https://codecov.io/github/pateketrueke/siguiente?branch=master)

```javascript
var chain = require('siguiente');

// next()-chained async tasks
chain([-1])
  .catch(function(err, next) {
    if (err) {
      console.log(err);
    }
    next();
  })
  .then(function(next, data) {
    data.push('modified');
    next(/* error */);
    // or throw new Error(...)
  })
  .run(function(err, data) {
    // err will be empty on success
    // data will be collected from data, i.e [-1, "modified"]
  });
```

Usage
-----

`chain(context)` will expose three methods:

- **catch(handler)** &mdash; Error handler for the chain
- **then(handler)** &mdash; Adds a subtask to chain
- **run(success)** &mdash; Initialize the chain

The created chain will be consumed until there are no more subtasks to invoke.

The constructor function can accept a **context** that will bind an extra argument on each callback.

> Siguiente **is not a replacement for promises** and has no compatibility for that
